version: "3.8"

services:

  go:
    container_name: go
    image: gotesttaskhalolab:1.0
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      pg:
        condition: service_healthy
      redis:
        condition: service_healthy
    links:
      - pg
      - redis

  pg:
    container_name: pg
    image: postgres:15-alpine3.18
    restart: always
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./db/pg:/var/lib/postgresql/data
    depends_on:
      - redis

  redis:
    container_name: redis
    image: redis:7-alpine3.16
    restart: always
    env_file:
      - .env
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}"
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - REDIS_DB=${REDIS_DB}
    volumes:
      - ./db/redis:/data


volumes:
  database_data:
    driver: local