version: "3.8"

services:

  go:
    container_name: go
    image: masedko/test-task-halo-lab:latest
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      pg:
        condition: service_healthy
    links:
      - pg
      - redis

  pg:
    container_name: pg
    image: postgres:15
    restart: always
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./data/pg:/var/lib/postgresql/data
    depends_on:
      - redis

  redis:
    container_name: redis
    image: redis:7-alpine3.16
    restart: always
    volumes:
      - ./data/redis:/data