definitions:
  dtos.Fish:
    properties:
      count:
        type: integer
      name:
        type: string
    required:
    - count
    - name
    type: object
  dtos.MessageResponse:
    properties:
      message:
        type: string
    type: object
  dtos.Temperature:
    properties:
      temperature:
        type: number
    required:
    - temperature
    type: object
  dtos.Transparency:
    properties:
      transparency:
        type: integer
    required:
    - transparency
    type: object
info:
  contact: {}
paths:
  /group/{groupName}/species:
    get:
      description: Full list of species (with counts) currently detected inside the
        group
      parameters:
      - description: Name of the group '{greekLetter}'
        in: path
        name: groupName
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Fish species with count
          schema:
            items:
              $ref: '#/definitions/dtos.Fish'
            type: array
        "400":
          description: Failed to return fish species
          schema:
            $ref: '#/definitions/dtos.MessageResponse'
        "422":
          description: Wrong groupName format
          schema:
            $ref: '#/definitions/dtos.MessageResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dtos.MessageResponse'
      summary: Get Species inside group
      tags:
      - group
  /group/{groupName}/species/top/{N}:
    get:
      description: List of top N species (with counts) currently detected inside the
        group
      parameters:
      - description: Name of the group '{greekLetter}'
        in: path
        name: groupName
        required: true
        type: string
      - description: Top N
        in: path
        name: "N"
        required: true
        type: integer
      - description: Start Date Time
        in: query
        name: fromDateTime
        type: string
      - description: End Date Time
        in: query
        name: untilDateTime
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Fish species with count
          schema:
            items:
              $ref: '#/definitions/dtos.Fish'
            type: array
        "400":
          description: Failed to return fish species
          schema:
            $ref: '#/definitions/dtos.MessageResponse'
        "422":
          description: Wrong groupName format
          schema:
            $ref: '#/definitions/dtos.MessageResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dtos.MessageResponse'
      summary: Get Top N Species inside group
      tags:
      - group
  /group/{groupName}/temperature/average:
    get:
      description: Calculates the temperature average for the specified group.
      parameters:
      - description: Name of the group '{greekLetter}'
        in: path
        name: groupName
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Temperature
          schema:
            $ref: '#/definitions/dtos.Temperature'
        "400":
          description: Failed to return temperature average
          schema:
            $ref: '#/definitions/dtos.MessageResponse'
        "422":
          description: Wrong groupName format
          schema:
            $ref: '#/definitions/dtos.MessageResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dtos.MessageResponse'
      summary: Calculate temperature average for a group
      tags:
      - group
  /group/{groupName}/transparency/average:
    get:
      description: Calculates the transparency average for the specified group.
      parameters:
      - description: Name of the group '{greekLetter}'
        in: path
        name: groupName
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Transparency
          schema:
            $ref: '#/definitions/dtos.Transparency'
        "400":
          description: Failed to return transparency average
          schema:
            $ref: '#/definitions/dtos.MessageResponse'
        "422":
          description: Wrong groupName format
          schema:
            $ref: '#/definitions/dtos.MessageResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dtos.MessageResponse'
      summary: Calculate transparency average for a group
      tags:
      - group
  /region/temperature/max:
    get:
      description: Current maximum temperature inside the region (a volume represented
        by the range of coordinates)
      parameters:
      - description: Minimum X coordinate
        in: query
        name: xMin
        required: true
        type: string
      - description: Maximum X coordinate
        in: query
        name: xMax
        required: true
        type: string
      - description: Minimum Y coordinate
        in: query
        name: yMin
        required: true
        type: string
      - description: Maximum Y coordinate
        in: query
        name: yMax
        required: true
        type: string
      - description: Minimum Z coordinate
        in: query
        name: zMin
        required: true
        type: string
      - description: Maximum Z coordinate
        in: query
        name: zMax
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Maximum temperature in volume
          schema:
            $ref: '#/definitions/dtos.Temperature'
        "400":
          description: Failed to return maximum temperature
          schema:
            $ref: '#/definitions/dtos.MessageResponse'
        "422":
          description: Wrong coordinates
          schema:
            $ref: '#/definitions/dtos.MessageResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dtos.MessageResponse'
      summary: Get Maximum temperature inside region
      tags:
      - region
  /region/temperature/min:
    get:
      description: Current minimum temperature inside the region (a volume represented
        by the range of coordinates)
      parameters:
      - description: Minimum X coordinate
        in: query
        name: xMin
        required: true
        type: string
      - description: Maximum X coordinate
        in: query
        name: xMax
        required: true
        type: string
      - description: Minimum Y coordinate
        in: query
        name: yMin
        required: true
        type: string
      - description: Maximum Y coordinate
        in: query
        name: yMax
        required: true
        type: string
      - description: Minimum Z coordinate
        in: query
        name: zMin
        required: true
        type: string
      - description: Maximum Z coordinate
        in: query
        name: zMax
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Minimum temperature in volume
          schema:
            $ref: '#/definitions/dtos.Temperature'
        "400":
          description: Failed to return minimum temperature
          schema:
            $ref: '#/definitions/dtos.MessageResponse'
        "422":
          description: Wrong coordinates
          schema:
            $ref: '#/definitions/dtos.MessageResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dtos.MessageResponse'
      summary: Get Minimum temperature inside region
      tags:
      - region
  /sensor/{codeName}/temperature/average:
    get:
      description: Average temperature detected by a particular sensor between the
        specified date/time pairs (UNIX timestamps)
      parameters:
      - description: Start Date Time
        in: query
        name: fromDateTime
        required: true
        type: string
      - description: End Date Time
        in: query
        name: untilDateTime
        required: true
        type: string
      - description: Name of the group '{greekLetter} {int}'
        in: path
        name: codeName
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Average temperature
          schema:
            $ref: '#/definitions/dtos.Temperature'
        "400":
          description: Failed to return average temperature
          schema:
            $ref: '#/definitions/dtos.MessageResponse'
        "422":
          description: Wrong UNIX time
          schema:
            $ref: '#/definitions/dtos.MessageResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dtos.MessageResponse'
      summary: Get average temperature inside region for particular sensor
      tags:
      - sensor
swagger: "2.0"
